autoencoder: 'None' # 'Autoencoder'
autoencoder_num_epochs: 15
hidden_size: 16           
autoencoder_lr: 0.001
autoencoder_saving_period: 10

actor_learning_rate: 1e-4
critic_learning_rate: 1e-3
             
